# Generated by Django 6.0.7 on 2026-07-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.CharField(default='chef-palm', max_length=30),
        ),
    ]
