# Generated by Django 6.0.7 on 2026-07-14 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('fatigue', 'Je suis fatigué(e), un truc simple'), ('economique', 'Je fais attention à mon budget'), ('energetique', "J'ai besoin d'énergie"), ('plaisir', "Je me fais plaisir aujourd'hui"), ('surprise', 'Surprends-moi')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('cereales', 'Céréales & féculents'), ('proteines', 'Protéines'), ('legumes', 'Légumes'), ('basiques', 'Basiques & sauces'), ('autre', 'Autre')], default='autre', max_length=20)),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Petit-déjeuner', 'Petit-déjeuner'), ('Déjeuner', 'Déjeuner'), ('Dîner', 'Dîner')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('difficulte', models.CharField(choices=[('Facile', 'Facile'), ('Moyen', 'Moyen'), ('Difficile', 'Difficile')], default='Facile', max_length=20)),
                ('duree_min', models.PositiveIntegerField(help_text='Temps de préparation en minutes')),
                ('budget_fcfa', models.PositiveIntegerField(help_text='Coût estimé en FCFA')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recettes/')),
                ('etapes', models.JSONField(default=list, help_text='Liste ordonnée des étapes de préparation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envies', models.ManyToManyField(related_name='recettes', to='recettes.envie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecetteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essentiel', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recette')),
            ],
            options={
                'unique_together': {('recette', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(related_name='recettes', through='recettes.RecetteIngredient', to='recettes.ingredient'),
        ),
        migrations.AddField(
            model_name='recette',
            name='repas',
            field=models.ManyToManyField(related_name='recettes', to='recettes.repas'),
        ),
    ]
