# Generated by Django 6.0.7 on 2026-07-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='etapes',
        ),
        migrations.CreateModel(
            name='EtapeRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='recettes.recette')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('recette', 'ordre')},
            },
        ),
    ]
