# Generated by Django 6.0.7 on 2026-07-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_remove_recette_etapes_etaperecette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='categorie',
            field=models.CharField(choices=[('cereales', 'Céréales & féculents'), ('legumes', 'Légumes'), ('fruits', 'Fruits'), ('viandes', 'Viandes'), ('poissons', 'Poissons & fruits de mer'), ('oeufs', 'Œuf & produits laitiers'), ('huiles', 'Huiles'), ('epices', 'Épices & assaisonnements'), ('condiments', 'Sauce & Condiments'), ('sec', 'Produits secs'), ('legumineux', 'Légumineux'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
