# Generated by Django 6.0.7 on 2026-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_alter_ingredient_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envie',
            name='code',
            field=models.CharField(choices=[('simple', 'Un truc simple et rapide'), ('economique', 'Je fais attention à mon budget'), ('energetique', "J'ai besoin d'énergie"), ('plaisir', "Je me fais plaisir aujourd'hui"), ('surprise', 'Surprends-moi'), ('gourmand', 'Un plat riche et copieux')], max_length=20, unique=True),
        ),
    ]
