export const recipes = [
  {
    id: "riz-saute-legumes",
    titre: "Riz sauté aux légumes",
    repas: ["Déjeuner", "Dîner"],
    envie: ["fatigue", "economique"],
    difficulte: "Facile",
    dureeMin: 20,
    budgetFCFA: 1200,
    ingredients: [
      { nom: "Riz", essentiel: true },
      { nom: "Tomate", essentiel: true },
      { nom: "Oignon", essentiel: true },
      { nom: "Huile", essentiel: true },
      { nom: "Poulet", essentiel: false },
      { nom: "Poivron", essentiel: false },
    ],
    etapes: [
      "Fais cuire le riz dans l'eau bouillante salée, puis égoutte.",
      "Coupe l'oignon et la tomate en petits morceaux.",
      "Fais chauffer l'huile, fais revenir l'oignon 2 minutes.",
      "Ajoute la tomate (et le poulet si tu en as), laisse cuire 5 minutes.",
      "Ajoute le riz, mélange bien pendant 3-4 minutes à feu vif.",
    ],
  },
  {
    id: "shakshuka",
    titre: "Sauce tomate aux œufs (shakshuka)",
    repas: ["Petit-déjeuner", "Déjeuner"],
    envie: ["fatigue", "energetique"],
    difficulte: "Facile",
    dureeMin: 15,
    budgetFCFA: 900,
    ingredients: [
      { nom: "Œufs", essentiel: true },
      { nom: "Tomate", essentiel: true },
      { nom: "Oignon", essentiel: true },
      { nom: "Piment", essentiel: true },
      { nom: "Poivron", essentiel: false },
      { nom: "Ail", essentiel: false },
    ],
    etapes: [
      "Fais revenir l'oignon émincé dans un peu d'huile.",
      "Ajoute la tomate coupée et le piment, laisse mijoter 8 minutes.",
      "Creuse des petits puits dans la sauce et casse les œufs dedans.",
      "Couvre et laisse cuire 5 minutes à feu doux, jusqu'à ce que les blancs soient pris.",
    ],
  },
  {
    id: "poulet-braise-igname",
    titre: "Poulet braisé & igname",
    repas: ["Déjeuner", "Dîner"],
    envie: ["plaisir", "surprise"],
    difficulte: "Moyen",
    dureeMin: 40,
    budgetFCFA: 2500,
    ingredients: [
      { nom: "Poulet", essentiel: true },
      { nom: "Igname", essentiel: true },
      { nom: "Oignon", essentiel: true },
      { nom: "Huile", essentiel: true },
      { nom: "Tomate", essentiel: false },
      { nom: "Piment", essentiel: false },
    ],
    etapes: [
      "Épluche et coupe l'igname en morceaux, fais bouillir 20 minutes.",
      "Assaisonne le poulet et fais-le dorer à l'huile chaude 10 minutes.",
      "Ajoute l'oignon (et la tomate si tu en as), laisse mijoter 15 minutes.",
      "Sers le poulet braisé avec l'igname bouilli.",
    ],
  },
  {
    id: "haricot-rouge",
    titre: "Haricot rouge sauce légère",
    repas: ["Déjeuner", "Dîner"],
    envie: ["economique", "energetique"],
    difficulte: "Facile",
    dureeMin: 30,
    budgetFCFA: 1000,
    ingredients: [
      { nom: "Haricot rouge", essentiel: true },
      { nom: "Oignon", essentiel: true },
      { nom: "Tomate", essentiel: true },
      { nom: "Huile", essentiel: true },
      { nom: "Carotte", essentiel: false },
    ],
    etapes: [
      "Fais cuire le haricot rouge (ou utilise une boîte déjà cuite).",
      "Fais revenir l'oignon et la tomate coupés dans l'huile.",
      "Ajoute le haricot cuit (et la carotte si tu en as), laisse mijoter 10 minutes.",
    ],
  },
  {
    id: "poisson-fume-epinard",
    titre: "Poisson fumé, épinard & riz",
    repas: ["Déjeuner", "Dîner"],
    envie: ["energetique", "plaisir"],
    difficulte: "Moyen",
    dureeMin: 30,
    budgetFCFA: 1800,
    ingredients: [
      { nom: "Riz", essentiel: true },
      { nom: "Poisson fumé", essentiel: true },
      { nom: "Épinard", essentiel: true },
      { nom: "Oignon", essentiel: true },
      { nom: "Ail", essentiel: false },
      { nom: "Gingembre", essentiel: false },
    ],
    etapes: [
      "Fais cuire le riz dans l'eau bouillante salée.",
      "Fais revenir l'oignon (et l'ail/gingembre) dans l'huile.",
      "Ajoute le poisson fumé émietté, laisse chauffer 5 minutes.",
      "Ajoute l'épinard lavé, laisse réduire 5 minutes.",
      "Sers sur le riz chaud.",
    ],
  },
  {
    id: "omelette-garnie",
    titre: "Omelette garnie & pain",
    repas: ["Petit-déjeuner"],
    envie: ["fatigue", "surprise"],
    difficulte: "Facile",
    dureeMin: 10,
    budgetFCFA: 700,
    ingredients: [
      { nom: "Œufs", essentiel: true },
      { nom: "Pain", essentiel: true },
      { nom: "Tomate", essentiel: true },
      { nom: "Oignon", essentiel: true },
      { nom: "Fromage", essentiel: false },
    ],
    etapes: [
      "Bats les œufs avec un peu de sel.",
      "Ajoute la tomate et l'oignon coupés fin (et le fromage si tu en as).",
      "Verse dans une poêle chaude huilée, cuis 3-4 minutes de chaque côté.",
      "Sers avec le pain.",
    ],
  },
];