# Generated by Django 6.0.7 on 2026-07-14 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_le', models.DateTimeField(auto_now_add=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recette')),
                ('repas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.repas')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historique',
                'ordering': ['-cuisine_le'],
            },
        ),
        migrations.CreateModel(
            name='MenuSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='recettes.recette')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ajoute_le'],
                'unique_together': {('utilisateur', 'recette')},
            },
        ),
        migrations.CreateModel(
            name='GardeManger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(blank=True, max_length=50)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garde_manger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ingredient__categorie', 'ingredient__nom'],
                'unique_together': {('utilisateur', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='MenuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10)),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.recette')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='cuisine.menusemaine')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('menu', 'jour')},
            },
        ),
    ]
