# Generated by Django 6.0.7 on 2026-07-15 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
        ('recettes', '0002_remove_recette_etapes_etaperecette'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menujour',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menujour',
            name='repas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recettes.repas'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menujour',
            unique_together={('menu', 'jour', 'repas')},
        ),
    ]
