# Generated by Django 6.0.7 on 2026-07-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_alter_menujour_unique_together_menujour_repas_and_more'),
        ('recettes', '0002_remove_recette_etapes_etaperecette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menujour',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AddField(
            model_name='menujour',
            name='date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menujour',
            unique_together={('menu', 'date', 'repas')},
        ),
        migrations.RemoveField(
            model_name='menujour',
            name='jour',
        ),
    ]
